apiVersion: v1
kind: ServiceAccount
metadata:
  name: lumigo-kubernetes-operator
  labels:
  {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lumigo
    app.kubernetes.io/part-of: lumigo