---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.lumigo.io
  resources:
  - lumigoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.lumigo.io
  resources:
  - lumigoes/finalizers
  verbs:
  - update
- apiGroups:
  - operator.lumigo.io
  resources:
  - lumigoes/status
  verbs:
  - get
  - patch
  - update
- # The Lumigo operator will access only secrets that are referenced by a Lumigo CRD
  apiGroups:
  - "" # Core API group
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
