apiVersion: v2
name: lumigo-operator
description: Chart to deploy the Lumigo Kubernetes Operator
type: application
keywords:
- observability
- monitoring
- distributed tracing
- opentelemetry
home: https://github.com/lumigo-io/lumigo-kubernetes-operator/
icon: https://raw.githubusercontent.com/lumigo-io/lumigo-kubernetes-operator/main/images/lumigo.png
version: '0'
appVersion: '0'
