debug:
  enabled: false
output:
  color: true
  showOperatorStatus: true
cluster:
  name:
controllerManager:
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.13.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 64Mi
  manager:
    image:
      repository: host.docker.internal:5000/controller
      tag: latest
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  telemetryProxy:
    image:
      repository: host.docker.internal:5000/telemetry-proxy
      tag: latest
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  replicas: 1
injectorWebhook:
  lumigoInjector:
    image:
      repository: public.ecr.aws/lumigo/lumigo-autotrace
      tag: latest
injectorWebhookService:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  type: ClusterIP
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  type: ClusterIP
endpoint:
  otlp:
    url: https://ga-otlp.lumigo-tracer-edge.golumigo.com
logCollection:
  enabled: false
fluent-bit:
  config:
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*_place__holder_*.log
          multiline.parser docker, cri
          Tag place__holder_namespace
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
    outputs: |
      [OUTPUT]
          Name opentelemetry
          Match place__holder_namespace
          Host mosheshaham-edge-app-us-west-2.mosheshaham.golumigo.com
          Port 443
          Logs_uri /v1/logs
          header Authorization LumigoToken t_186eb52a329344cdb0d6c
          log_response_payload true
          Tls on
  hotReload:
    enabled: true