apiVersion: operator.lumigo.io/v1alpha1
kind: Lumigo
metadata:
  labels:
    app.kubernetes.io/name: lumigo
    app.kubernetes.io/instance: lumigo
    app.kubernetes.io/part-of: lumigo
    app.kubernetes.io/created-by: lumigo
  name: lumigo
spec:
  lumigoToken:
    secretRef:
      name: lumigo-credentials
      key: token
