apiVersion: v1
kind: Secret
metadata:
  name: lumigo-credentials
stringData:
  # Kubectl won't allow you to deploy this dangling anchor.
  # Get the actual value from Lumigo following this documentation: https://docs.lumigo.io/docs/lumigo-tokens
  token: *lumigo-token # Example: t_123456789012345678901
---
apiVersion: operator.lumigo.io/v1alpha1
kind: Lumigo
metadata:
  labels:
    app.kubernetes.io/name: lumigo
    app.kubernetes.io/instance: lumigo-sample
    app.kubernetes.io/part-of: lumigo
    app.kubernetes.io/created-by: lumigo
  name: lumigo-sample
spec:
  lumigoToken:
    secretRef:
      name: lumigo-credentials
      key: token
