receivers:
  otlp:
    protocols:
      http:
        auth:
          authenticator: lumigoauth
        include_metadata: true # Needed by `headers_setter/lumigo`

extensions:
  health_check:
  lumigoauth:
  headers_setter/lumigo:
    headers:
    # Use the same authorization header as the one accompanying
    # the request received in the receiver. It needs the
    # `include_metadata: true` parameter in the `otlp` exporter
    - key: authorization
      from_context: Authorization

exporters:
  otlphttp/lumigo:
    endpoint: https://ga-otlp.lumigo-tracer-edge.golumigo.com
    auth:
      authenticator: headers_setter/lumigo
  logging:
    loglevel: debug
    sampling_initial: 1
    sampling_thereafter: 1

# We cannot add the Batch processor, as it breaks the `headers_setter/lumigo`
# see https://github.com/open-telemetry/opentelemetry-collector/issues/4544
processors: {}

service:
  extensions:
  - headers_setter/lumigo
  - health_check
  - lumigoauth
  pipelines:
    traces:
      receivers:
      - otlp
      processors: []
      exporters:
      - otlphttp/lumigo
      - logging
  telemetry:
    logs:
      level: "debug"
